version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    ports:
      - 8088:8080
    environment:
      KEYCLOAK_USER: ${KEYCLOACK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOACK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm.json
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./realm.json:/tmp/realm.json
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local