version: '3.7'

services:
  mongo-db:
    container_name: mongoDB
    image: bitnami/mongodb:${MONGO_VERSION:-latest}
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=mongouser
      - MONGODB_DATABASE=corona_attendance_report
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "mongo_data:/data/db"
    networks:
      - ${GLOBAL_NETWORK:-mongo}

volumes:
  mongo_data:
    driver: local