keycloak:
  realm: corona-attendance-report
  auth-server-url: https://sso.mrtimeey.de/auth
  ssl-required: external
  resource: corona-attendance-report-server
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  credentials:
    secret: '{cipher}705553b50dde871ca1e9c32222c5e027666f5569ad2dd2112e093b7ef4b2d831edaaa979265fbf2b04e1411fdc662d543e94efb823042ee1a33b48a1fef93425'
spring:
  data:
    mongodb:
      host: localhost
      username: mongouser
      password: <set-value-through-vm-options>
      database: corona_attendance_report
